name: 🚀 Deploy App

on:
  push:
    branches:
      - main
      - hom

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, gd, zip, pgsql

      - name: 🎯 Determina ambiente e executa Deploy
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            ENV="production"
          else
            ENV="staging"
          fi

          bash scripts/deploy.sh $ENV